name: Static Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
          
      - run: composer update --prefer-dist --no-progress
      
      - run: composer phpstan -- --no-progress
      
  style:
    name: PHP-CS-Fixer Analysis
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1
    steps:
      - uses: actions/checkout@v2
      
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
          
      - run: composer update --prefer-dist --no-progress
      
      - run: composer lint
      
