name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0, 8.1, 8.2, 8.3 ]
        laravel: [ ^8.12, ^9.0, ^10.0 ]
        exclude:
          - php: 8.3
            laravel: ^8.12
          - php: 8.3
            laravel: ^9.0
          - php: 8.2
            laravel: ^8.12
          - php: 8.0
            laravel: ^10.0
    name: PHP=${{ matrix.php }} LARAVEL=${{ matrix.laravel }}
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1
      XDEBUG_MODE: coverage
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: composer test -- --coverage-clover ./coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
